# Generated by Django 4.2.1 on 2023-08-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('awards_id', models.IntegerField(primary_key=True, serialize=False)),
                ('awards_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='TypeAwards',
            fields=[
                ('type_awards_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_awards', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type_awards',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emplyees_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('hire', models.IntegerField()),
                ('kgtu_hire', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('kgtu_experience', models.IntegerField()),
                ('fk_awards', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tables.awards')),
                ('fk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.post')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.AddField(
            model_name='awards',
            name='fk_type_awards',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tables.typeawards'),
        ),
    ]
